/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function captureDisplay(index: number, maxLongEdge: number, crop?: CropRect | undefined | null): Promise<CaptureResult>

export interface CaptureResult {
  png: Buffer
  /** 缩放后（PNG 实际）宽度 */
  width: number
  /** 缩放后（PNG 实际）高度 */
  height: number
  /** 原生 DPI 缩放比（纯信息性，不参与坐标换算；换算比 = width/phys_width 现派生） */
  dpiScale: number
  originX: number
  originY: number
  /** 原始物理宽度 */
  physWidth: number
  /** 原始物理高度 */
  physHeight: number
}

/**
 * 区域裁剪框（region zoom）。坐标为**虚拟桌面物理像素**（多显示器环境下原点可为负），
 * 与 core 侧约定一致：裁剪时先减去显示器原点换算成局部坐标，越界部分 clamp 到显示器范围。
 */
export interface CropRect {
  x: number
  y: number
  width: number
  height: number
}

export declare function cursorPosition(): Promise<Array<number>>

/** 诊断：某点的宿主命中测试码（非宿主返回 None；HT_UNKNOWN=i32::MIN 表示超时/失败） */
export declare function debugHitTest(x: number, y: number): number | null

/** 诊断：某点命中链路全量信息 [命中窗口pid, 根窗口pid, 是否在保护集, 命中码或-999] */
export declare function debugProbe(x: number, y: number): Array<number>

export declare function debugProtection(): DebugProtection

/**
 * 实测闸门：保护 PID 集 + 宿主窗口矩形清单（调试用，不进工具链）
 * 窗口枚举亚毫秒级——保持同步导出
 */
export interface DebugProtection {
  pids: Array<number>
  hostWindows: Array<string>
  allWindows: Array<string>
}

export interface DisplayInfo {
  index: number
  name: string
  x: number
  y: number
  width: number
  height: number
  /**
   * 原生 DPI 缩放比（如 150% → 1.5）。纯信息性，不参与坐标换算——
   * 图像↔物理换算由消费方用 width/phys_width 现派生（契约只运输实测事实）
   */
  dpiScale: number
  isPrimary: boolean
}

/**
 * 焦点配方：IsIconic→SW_RESTORE → AllowSetForegroundWindow → AttachThreadInput
 * 双线程 → SetForegroundWindow/BringWindowToTop/SetWindowPos → 逆序 detach（RAII）→
 * GetForegroundWindow 回读验证（100ms×3）
 */
export declare function focusWindow(hwnd: number): Promise<void>

export declare function key(combo: string): Promise<void>

export declare function listDisplays(): Promise<Array<DisplayInfo>>

export declare function mouseClick(x: number, y: number, button: string, count: number): Promise<void>

export declare function mouseDrag(fromX: number, fromY: number, toX: number, toY: number): Promise<void>

export declare function mouseMove(x: number, y: number): Promise<void>

export declare function preflight(): Promise<Preflight>

export interface Preflight {
  /** 用户物理按下 ESC（GetAsyncKeyState 0x8000 当前态位） */
  escPressed: boolean
  cursorX: number
  cursorY: number
}

export declare function releaseAllInputs(): Promise<void>

export declare function scroll(x: number, y: number, dx: number, dy: number): Promise<void>

/**
 * 审批挂起状态推送（core 审批聚合器 → shell → 本导出；自审批攻击面封堵的数据源）
 * 纯内存写——保持同步导出
 */
export declare function setApprovalPending(pending: boolean): void

/**
 * 兄弟 chill 实例根 PID 注入（core 实例注册表 → shell → 本导出；全量替换语义）
 * 纯内存写，亚微秒级——保持同步导出
 */
export declare function setProtectedExtraPids(pids: Array<number>): void

export declare function typeText(text: string): Promise<void>

export interface UiElementInfo {
  /** 快照内编号，从 1 开始 */
  label: number
  name: string
  /** 本地化无关的英文控件类型名（ControlType 的 Debug 名） */
  controlType: string
  /** bbox，物理像素（进程已 Per-Monitor V2） */
  x: number
  y: number
  width: number
  height: number
  hwnd: number
  /** Vec<i32> 以 "." 连接序列化 */
  runtimeId: string
  hasInvoke: boolean
  hasValue: boolean
  hasToggle: boolean
  /**
   * 元素属于 chill 宿主进程树（ProcessId 判定，不用 hwnd——Chromium 渲染树元素 hwnd 常为 0）；
   * 宿主元素保留在快照中（set_value 带外写文本是合法窄通道），但 invoke 会被硬门拒绝
   */
  isHost: boolean
}

export declare function uiInvoke(runtimeId: string): Promise<void>

export declare function uiSetValue(runtimeId: string, text: string): Promise<void>

export declare function uiSnapshot(scope: string): Promise<Array<UiElementInfo>>

/**
 * 窗口管理原语（RPA 式：PAD/UiPath 的 Move/Resize/SetState/Close 对应物）。
 * 操作集封闭：move/resize/set_bounds/minimize/maximize/restore + close（仅非宿主）。
 * 宿主护栏：close 对保护集窗口永拒（与注入门同一 protect.rs 事实源）；强杀永远不进本动作。
 */
export declare function windowManage(hwnd: number, op: string, rect?: CropRect | undefined | null): Promise<void>
