export * from './types'
export * from './utils'
export * from './interfaces'
export * from './implementations'
export * from './orchestrator'
export * from './skills'
export * from './services/mcp'
export * from './services/history'
export * from './services/builtInTools'
export * from './services/toolExecutorRegistry'
export * from './services/builtInToolExecutor'
export * from './services/toolExecutors'
export * from './services/toolExecutorFactory'
export * from './services/resourceToolAdapter'
export * from './services/a2aClient'
export * from './services/coze/CozeAgentAdapter'
export * from './services/models'
export * from './services/credentials'
export * from './services/codeExecutor'
export * from './services/secureStorageService'
export * from './services/attachmentManager'
export * from './services/mediaContentBuilder'
export * from './services/toolResultGuard'
export * from './services/selectedModelsService'
export * from './services/memory'
export * from './services/knowledge'
export * from './services/improvementProposer'
export * from './services/improvementLedger'
export * from './services/ImprovementProposalManager'
export * from './services/agentInstructions'
export * from './services/mcpAutoReconnect'
export * from './services/sessionTitleService'
export * from './services/delegation/delegationTools'
export * from './services/delegation/resolveCancelTarget'
export * from './services/delegation/quota'
export * from './services/team/teamPolicy'
export * from './services/team/teamLedgerFormat'
export * from './services/team/runtimeProjection'
export * from './services/team/teamContextLine'
export * from './services/team/teamWatchdog'
export * from './services/delegation/taskRegistry'
export * from './services/delegation/delegationPrompt'
export * from './services/delegation/workflowRunTool'
export * from './services/approvals'
export * from './services/askChannel'
// 多会话基座（迭代 1）：SessionRegistry 纯容器 + SessionScope 归因上下文（Node-free，双入口可导出）
export * from './services/sessionRegistry'
export * from './services/approvalPresentation'
export * from './services/writeBoundary'
export * from './services/backupStore'
export * from './services/sessionSearch'
export * from './services/compaction/compactionService'
// 生命周期 hooks（阶段 1）：平台无关（执行通道 IHookProcessRunner 由壳层注入），双入口均可导出
export * from './services/hooks'
// 定时任务（阶段 1）：平台无关（TaskStore 走 IFileSystemProvider，引擎接线在 ChatEngine），双入口均可导出
export * from './services/scheduler'
// 定向路由的盘上查询（M3：project 任务「该目录最近会话」数据源，sessionIndex 域）
export { latestSessionIdInDir } from './services/sessionIndex'
// [M3.7 下沉] Node 直执行 hook 通道（CLI/daemon 共用；仅 Node 入口导出——child_process 不进渲染层产物）
export { NodeHookProcessRunner, expandHomeCommand } from './services/hooks/nodeHookProcessRunner'
// [M3 下沉] Node 侧 IFileSystemProvider（CLI/Electron/daemon 三消费者合并超集；仅 Node 入口导出）
export { NodeFileSystemProvider } from './implementations/NodeFileSystemProvider'
// 目标文档持久化（Node-only：fs/os/path；对照 plans 模式，仅 Node 入口导出）
export * from './services/goalPersistence'
// ChatEngine 统一对话路径（T2）：engine 本体平台无关；Node 侧装配含 Node-only 依赖，仅 Node 入口导出
export * from './engine'
export * from './engine/nodeFactory'
export * from './execution'
export * from './a2a'
export * from './persistence'
export * from './workflow/shared'
export * from './workflow/TaskListManager'
export * from './workflow/workflowGraphBuilder'
export * from './workflow/agentNodeExecutor'
export * from './workflow/workflowExecutor'
// 命名工作流 DSL + 加载层(M1)
export * from './workflow/dsl/types'
export * from './workflow/dsl/workflowParser'
export * from './workflow/dsl/workflowSerializer'
export * from './services/assets/assetDirectory'
export * from './services/workflow/WorkflowTemplateService'
export * from './services/workflow/legacyWorkflowMigrator'
export * from './services/workflow/workflowRunStore'
// 固定团队(M1):DSL + 加载层 + use_team 工具
export * from './team/types'
export * from './team/teamSerializer'
export * from './services/team/TeamTemplateService'
export * from './services/team/useTeamTool'
export * from './services/team/TeamRuntimeService'
export * from './services/team/teamRuntimeTypes'
// 共享看板(V1.5-V1.7:会话级板容器/settle 桥/板工具/投影;看板类型经 teamRuntimeTypes re-export 保兼容,不重复导出)
export type { BoardState, BoardCaller, BoardSettleOutcome } from './services/board/boardTypes'
export * from './services/board/SessionBoardService'
export * from './services/board/boardStore'
export * from './services/board/boardTool'
export * from './services/board/boardProjection'
export * from './services/board/boardSettleBridge'
export * from './services/board/boardAskBridge'
export * from './services/delegation/steerTaskTool'
export * from './services/delegation/escalateTool'
// M8：命令面注册表（纯数据+校验+执行机械，Node-free——壳经 deps 注入服务引用）
export * from './services/commands/commandSurface'
export * from './services/desktopControl'// relay 模块（M2）：红线——services/relay/** 必须保持 Node-free（禁 node:*/Buffer，renderer/RN 安全），按文件导出不用目录 barrel
export * from './services/relay/envelope'
export * from './services/relay/PairingManager'
export * from './services/relay/RelayBridge'
export * from './services/relay/RelayTransport'
export * from './services/relay/relayLock'
// 读长连主动探活策略（常数+判死纯函数，Node-free；壳侧定时器编排引用）
export * from './services/relay/wsKeepalive'
// file.* 协议族：传输重组器（纯状态机，Node-free）
export * from './services/relay/fileTransfer'
// 工作计划树：投影 SSOT 与镜像纯逻辑（纯函数、Node-free，renderer/RN 安全）
export * from './services/workplan/workPlanTree'
export * from './services/workplan/workPlanMirror'
// M4：relay 环境装配（接触 eventBus/approvals 单例，仅 Node 主入口导出，不进 index.renderer.ts）
export * from './services/relayEngineWiring'
// M6：双端会话同步纯逻辑（读文件真相源 sessions-index/projects.json，仅 Node 主入口导出）
export * from './services/SessionSyncService'

// 统一文本匹配引擎（replace/insert/delete_content 共用，Node-free，双壳同一套匹配语义）
export * from './services/positioning/textMatcher'
// 原生模块影子加载判定（.node 影子复制的判定唯一事实点，Node-free，fs 接线归壳适配器）
export * from './services/nativeShadow'
// 换版令牌（版本切换接续规划 M1.2）：switcher 单点写，CLI/Electron/Web 三壳共用读/watch
export * from './services/versionToken'
