/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function captureDisplay(index: number, maxLongEdge: number): CaptureResult

export interface CaptureResult {
  png: Buffer
  /** 缩放后（PNG 实际）宽度 */
  width: number
  /** 缩放后（PNG 实际）高度 */
  height: number
  /** 原生 DPI 缩放比（纯信息性，不参与坐标换算；换算比 = width/phys_width 现派生） */
  dpiScale: number
  originX: number
  originY: number
  /** 原始物理宽度 */
  physWidth: number
  /** 原始物理高度 */
  physHeight: number
}

export declare function cursorPosition(): Array<number>

export interface DisplayInfo {
  index: number
  name: string
  x: number
  y: number
  width: number
  height: number
  /**
   * 原生 DPI 缩放比（如 150% → 1.5）。纯信息性，不参与坐标换算——
   * 图像↔物理换算由消费方用 width/phys_width 现派生（契约只运输实测事实）
   */
  dpiScale: number
  isPrimary: boolean
}

/**
 * 焦点配方：IsIconic→SW_RESTORE → AllowSetForegroundWindow → AttachThreadInput
 * 双线程 → SetForegroundWindow/BringWindowToTop/SetWindowPos → 逆序 detach（RAII）→
 * GetForegroundWindow 回读验证（100ms×3）
 */
export declare function focusWindow(hwnd: number): void

export declare function key(combo: string): void

export declare function listDisplays(): Array<DisplayInfo>

export declare function mouseClick(x: number, y: number, button: string, count: number): void

export declare function mouseDrag(fromX: number, fromY: number, toX: number, toY: number): void

export declare function mouseMove(x: number, y: number): void

export declare function scroll(x: number, y: number, dx: number, dy: number): void

export declare function typeText(text: string): void

export interface UiElementInfo {
  /** 快照内编号，从 1 开始 */
  label: number
  name: string
  /** 本地化无关的英文控件类型名（ControlType 的 Debug 名） */
  controlType: string
  /** bbox，物理像素（进程已 Per-Monitor V2） */
  x: number
  y: number
  width: number
  height: number
  hwnd: number
  /** Vec<i32> 以 "." 连接序列化 */
  runtimeId: string
  hasInvoke: boolean
  hasValue: boolean
  hasToggle: boolean
}

export declare function uiInvoke(runtimeId: string): void

export declare function uiSetValue(runtimeId: string, text: string): void

export declare function uiSnapshot(scope: string): Array<UiElementInfo>
